### ISSUE TITLE
Error getting deviceType: 

### ISSUE THREAD

**Issue by quicklywilliam** [netmanchris/pyawair#13] opened 2018-08-20 14:34 UTC
I get the following error when trying to use the latest version of pyawair:
`
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/sensor/awair.py", line 60, in setup_platform
    awair_poller = AwairDev(name, awair_auth, refresh_rate)
  File "/srv/homeassistant/lib/python3.6/site-packages/pyawair/objects.py", line 32, in __init__
    False)['deviceType']  # get the device type
TypeError: 'bool' object is not subscriptable
`

**Comment by netmanchris** [comment] 2018-08-20 14:39
hey @quicklywilliam  This is still under development and testing so please have patience while we get this worked out.   @danielsjf  is taking lead on the object class for the Hass work and put together the Hass drive that I assume you're using. 

@danielsjf  Can you take a look at this and let us know what you think? If you get it figured out and want to add a test to prevent regressions that would be great too. :)

**Comment by danielsjf** [comment] 2018-08-20 16:53
@quicklywilliam I had the same issue as you and a reboot fixed it for me. Currently we don't support asyncio yet (asynchronous calls). I suspect that this is because synchronous calls have a max time limit. During the first call, pyawair is installed and this violates the limit.

**Comment by netmanchris** [comment] 2018-08-24 16:14
@quicklywilliam Hey William, Did you get this solved? I'd like to close this issue if possible.

thanks!

Chris

**Comment by quicklywilliam** [comment] 2018-08-26 02:14
No dice after restarting – got the same error.

**Comment by danielsjf** [comment] 2018-08-26 09:10
Did you restart Hass io or the full device? Since for me it was the full device that fixed it. Also it won't work anymore due to a change in the API. The current data endpoint that was used is now in a higher tier. Therefore you'll probably don't have the right permissions like me. Could you check the error again to make sure it is the same? Just to be sure.

**Comment by quicklywilliam** [comment] 2018-08-26 17:18
I restarted the device, same error.

**Comment by danielsjf** [comment] 2018-08-26 20:40
I'll look at it in course of this week. In the meantime, could you log the debug messages to see where it gets?

You can add the following lines to your configuration:
logger:
  default: critical
  logs:
    homeassistant.custom_components.sensor.awair: debug
    custom_components.sensor.awair: debug

Sorry for formatting, I'm on my phone now.

**Comment by danielsjf** [comment] 2018-08-26 20:43
This should give you the logs. You can find them by clicking on the i (with a circle) symbol. All the way in the bottom there is a refresh button to load the logs.

**Comment by quicklywilliam** [comment] 2018-09-03 01:28
I'm getting the same message with no further details in the logs. Also tried upgrading to pyawair 0.0.8…

**Comment by quicklywilliam** [comment] 2018-09-03 01:52
Looking further into this I discovered that my device name was wrong in my awair_component configuration. So it would appear that the way to trigger this bug is to attempt to create an AwairDev with a non-existent name?

**Comment by danielsjf** [comment] 2018-09-03 07:14
I opened a separate issue which is more actionable. @netmanchris I don't seem to have the rights, so could you close it?

**Comment by netmanchris** [comment] 2018-09-05 15:46
@danielsjf Added you as a collaborator on the repo and also closed the issue. Let me know if you don't see the invite.

**Closed by netmanchris** 2018-09-05 15:46 UTC
Labels: bug
